# Caliopen configuration file to run REST API server in a docker container
#
# Storage services must be accessible using FQDN:
#  - cassandra.dev.caliopen.org
#  - es.dev.caliopen.org
#  - redis.dev.caliopen.org (see pyramid configuration file)
#
# Make your /etc/hosts lie or user docker containers from docker-compose.yml in /devtools

delivery_agent:
    direct: True

elasticsearch:
    url: http://es.dev.caliopen.org:9200

cassandra:
    keyspace: caliopen
    hosts:
        - 'cassandra.dev.caliopen.org'
    consistency_level: 1
    protocol_version: 3

lmtp:
    port: 4025
    bind_address: 0.0.0.0

broker:
    port: 2525
    host: broker.dev.caliopen.org

message_queue:
    port: 4222
    host: nats.dev.caliopen.org

object_store:
    db_size_limit: 1048576
    service: s3
    endpoint: minio.dev.caliopen.org:9090
    access_key: CALIOPEN_ACCESS_KEY_
    secret_key: CALIOPEN_SECRET_KEY_BE_GOOD_AND_LIVE_OLD
    location: eu-fr-localhost

system:
    default_tags:
        -
            name: INBOX
            background: '#000000'
            color: black
        -
            name: SPAM
            background: '#AAAAAA'
            color: white
        -
            name: IMPORTANT
            background: '#FF0000'
            color: white

default_domain: caliopen.local

internal_domains:
    - caliopen.local
    - brainstorm.fr

blacklistes:
    mx:
        - mx.bad.guy
