## SMTP config ##
AppConfig:
  version: 0.1.0 #to be moved into a general version file
  allowed_hosts:
  - localhost
  - caliopen.local
  - caliopen.org
  primary_mail_host: caliopen.org
  servers:
  - is_enabled: true
    host_name: localhost
    max_size: 20971520
    timeout: 180
    listen_interface: 127.0.0.1:2525
    start_tls_on: false
    tls_always_on: false
    max_clients: 1000

## LDA config ##
LDAConfig:
  lda_workers_size: 2
  log_received_mails: true
  backend_name: cassandra # backend to save raw emails to (inbound & outbound)
  backend_settings:
    hosts:
    - 127.0.0.1
    keyspace: caliopen
    consistency_level: 1
  # nats config
  nats_url: nats://localhost:4222
  nats_topic: inboundSMTP

## Outbound Agent config ##
OutConfig:
  submit_address: 127.0.0.1
  submit_port: 2500
  submit_user:
  submit_password:
  nats_url: nats://localhost:4222
  nats_topic: outboundSMTP
  nats_listeners: 1 # number of concurrent nats listeners
  mta_workers: 2  # number of concurrent mta connexions