## SMTP config ##
AppConfig:
  allowed_hosts:
  - localhost
  - caliopen.local
  - caliopen.org
  primary_mail_host: caliopen.org
  inbound_servers: # only one allowed for now
  - is_enabled: true
    host_name: localhost
    max_size: 20971520 # max authorized size for emails in bytes
    timeout: 180
    listen_interface: 0.0.0.0:2525
    start_tls_on: false
    tls_always_on: false
    max_clients: 1000
  #submit is the MTA to connect to for final delivery (postfix for example)
  submit_address: smtp.dev.caliopen.org
  submit_port: 10025
  submit_user:
  submit_password:
  submit_workers: 2  # number of concurrent connexions to submit MTA

## LDA (Email broker) config ##
LDAConfig:
  broker_type: smtp # types are : smtp, imap, mailboxe, etc.
  nats_url: nats://nats.dev.caliopen.org:4222
  nats_queue: SMTPqueue # NATS group queue for nats subscribers to share jobs
  store_name: cassandra # backend to store raw emails and messages (inbound & outbound)
  store_settings:
    hosts: # many allowed
    - cassandra.dev.caliopen.org
    keyspace: caliopen
    consistency_level: 1
    raw_size_limit: 124 # max size for objects in db. Use S3 interface if larger.
  s3_service: minio
  s3_settings:
    endpoint: minio.dev.caliopen.org:9000
    access_key: PPX4CASO14T5M3ON33WB
    secret_key: BA+FsfZOjpX+3LTjJNukZ3Juop+1iDSgu2NET4ZW
    raw_msg_location: eu-fr-localhost # S3 region. Not relevant if minio server is used.
    raw_msg_bucket: raw-messages # bucket name to put raw messages to
  index_name: elasticsearch # backend to index messages (inbound & outbound)
  index_settings:
    urls: # many allowed
    - http://es.dev.caliopen.org:9200

  #inbound
  in_topic: inboundSMTP # NATS topic to listen to
  lda_workers_size: 2 # number of concurrent workers
  log_received_mails: true

  # outbound
  out_topic: outboundSMTP # NATS topic to listen to
  nats_listeners: 2 # number of concurrent nats listeners
