---
type: object
properties:
  default_locale:
    type: string
    default: fr-FR
  message_display_format:
    type: string
    default: rich_text
  contact_display_order:
    type: string
    default: given_name
  contact_display_format:
    type: string
    default: family_name, given_name
  notification_enabled:
    type: boolean
    default: true
  notification_message_preview:
    type: string
    default: always
  notification_sound_enabled:
    type: boolean
    default: false
  notification_delay_disappear:
    type: integer
    default: 10
