---
type: object
properties:
  default_locale:
    type: string
  message_display_format:
    type: string
  contact_display_order:
    type: string
  notification_enabled:
    type: boolean
  notification_message_preview:
    type: string
  notification_sound_enabled:
    type: boolean
  notification_delay_disappear:
    type: integer
